//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioControlProteinas
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://simpleprogrammer.com")]
    public partial class User : object
    {
        
        private string NameField;
        
        private int GoalField;
        
        private int TotalField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Goal
        {
            get
            {
                return this.GoalField;
            }
            set
            {
                this.GoalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://simpleprogrammer.com", ConfigurationName="ServicioControlProteinas.ProteinTrackingServiceSoap")]
    public interface ProteinTrackingServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleprogrammer.com/AddProtein", ReplyAction="*")]
        int AddProtein(int amount, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleprogrammer.com/AddProtein", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddProteinAsync(int amount, int userId);
        
        // CODEGEN: Generating message contract since element name name from namespace http://simpleprogrammer.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleprogrammer.com/AddUser", ReplyAction="*")]
        ServicioControlProteinas.AddUserResponse AddUser(ServicioControlProteinas.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleprogrammer.com/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioControlProteinas.AddUserResponse> AddUserAsync(ServicioControlProteinas.AddUserRequest request);
        
        // CODEGEN: Generating message contract since element name ListUsersResult from namespace http://simpleprogrammer.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleprogrammer.com/ListUsers", ReplyAction="*")]
        ServicioControlProteinas.ListUsersResponse ListUsers(ServicioControlProteinas.ListUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleprogrammer.com/ListUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioControlProteinas.ListUsersResponse> ListUsersAsync(ServicioControlProteinas.ListUsersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://simpleprogrammer.com", Order=0)]
        public ServicioControlProteinas.AddUserRequestBody Body;
        
        public AddUserRequest()
        {
        }
        
        public AddUserRequest(ServicioControlProteinas.AddUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://simpleprogrammer.com")]
    public partial class AddUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int goal;
        
        public AddUserRequestBody()
        {
        }
        
        public AddUserRequestBody(string name, int goal)
        {
            this.name = name;
            this.goal = goal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://simpleprogrammer.com", Order=0)]
        public ServicioControlProteinas.AddUserResponseBody Body;
        
        public AddUserResponse()
        {
        }
        
        public AddUserResponse(ServicioControlProteinas.AddUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://simpleprogrammer.com")]
    public partial class AddUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddUserResult;
        
        public AddUserResponseBody()
        {
        }
        
        public AddUserResponseBody(int AddUserResult)
        {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListUsersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListUsers", Namespace="http://simpleprogrammer.com", Order=0)]
        public ServicioControlProteinas.ListUsersRequestBody Body;
        
        public ListUsersRequest()
        {
        }
        
        public ListUsersRequest(ServicioControlProteinas.ListUsersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListUsersRequestBody
    {
        
        public ListUsersRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListUsersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListUsersResponse", Namespace="http://simpleprogrammer.com", Order=0)]
        public ServicioControlProteinas.ListUsersResponseBody Body;
        
        public ListUsersResponse()
        {
        }
        
        public ListUsersResponse(ServicioControlProteinas.ListUsersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://simpleprogrammer.com")]
    public partial class ListUsersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioControlProteinas.User[] ListUsersResult;
        
        public ListUsersResponseBody()
        {
        }
        
        public ListUsersResponseBody(ServicioControlProteinas.User[] ListUsersResult)
        {
            this.ListUsersResult = ListUsersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ProteinTrackingServiceSoapChannel : ServicioControlProteinas.ProteinTrackingServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ProteinTrackingServiceSoapClient : System.ServiceModel.ClientBase<ServicioControlProteinas.ProteinTrackingServiceSoap>, ServicioControlProteinas.ProteinTrackingServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProteinTrackingServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ProteinTrackingServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ProteinTrackingServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProteinTrackingServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProteinTrackingServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProteinTrackingServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProteinTrackingServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProteinTrackingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int AddProtein(int amount, int userId)
        {
            return base.Channel.AddProtein(amount, userId);
        }
        
        public System.Threading.Tasks.Task<int> AddProteinAsync(int amount, int userId)
        {
            return base.Channel.AddProteinAsync(amount, userId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioControlProteinas.AddUserResponse ServicioControlProteinas.ProteinTrackingServiceSoap.AddUser(ServicioControlProteinas.AddUserRequest request)
        {
            return base.Channel.AddUser(request);
        }
        
        public int AddUser(string name, int goal)
        {
            ServicioControlProteinas.AddUserRequest inValue = new ServicioControlProteinas.AddUserRequest();
            inValue.Body = new ServicioControlProteinas.AddUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.goal = goal;
            ServicioControlProteinas.AddUserResponse retVal = ((ServicioControlProteinas.ProteinTrackingServiceSoap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioControlProteinas.AddUserResponse> ServicioControlProteinas.ProteinTrackingServiceSoap.AddUserAsync(ServicioControlProteinas.AddUserRequest request)
        {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioControlProteinas.AddUserResponse> AddUserAsync(string name, int goal)
        {
            ServicioControlProteinas.AddUserRequest inValue = new ServicioControlProteinas.AddUserRequest();
            inValue.Body = new ServicioControlProteinas.AddUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.goal = goal;
            return ((ServicioControlProteinas.ProteinTrackingServiceSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioControlProteinas.ListUsersResponse ServicioControlProteinas.ProteinTrackingServiceSoap.ListUsers(ServicioControlProteinas.ListUsersRequest request)
        {
            return base.Channel.ListUsers(request);
        }
        
        public ServicioControlProteinas.User[] ListUsers()
        {
            ServicioControlProteinas.ListUsersRequest inValue = new ServicioControlProteinas.ListUsersRequest();
            inValue.Body = new ServicioControlProteinas.ListUsersRequestBody();
            ServicioControlProteinas.ListUsersResponse retVal = ((ServicioControlProteinas.ProteinTrackingServiceSoap)(this)).ListUsers(inValue);
            return retVal.Body.ListUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioControlProteinas.ListUsersResponse> ServicioControlProteinas.ProteinTrackingServiceSoap.ListUsersAsync(ServicioControlProteinas.ListUsersRequest request)
        {
            return base.Channel.ListUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioControlProteinas.ListUsersResponse> ListUsersAsync()
        {
            ServicioControlProteinas.ListUsersRequest inValue = new ServicioControlProteinas.ListUsersRequest();
            inValue.Body = new ServicioControlProteinas.ListUsersRequestBody();
            return ((ServicioControlProteinas.ProteinTrackingServiceSoap)(this)).ListUsersAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProteinTrackingServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ProteinTrackingServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProteinTrackingServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64018/ProteinTrackingService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ProteinTrackingServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64018/ProteinTrackingService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ProteinTrackingServiceSoap,
            
            ProteinTrackingServiceSoap12,
        }
    }
}
